name: Build EffDirEditor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt

      - name: Run tests (basic run)
        run: python main.py || echo "Main ran with exit code %errorlevel%"

      - name: Build EXE with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py --name EffDirEditor

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: EffDirEditor-exe
          path: dist/EffDirEditor.exe
