
name: Build and Release EffDirEditor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name "EffDirEditor" main.py
          mkdir build_artifact
          copy dist\EffDirEditor.exe build_artifact\EffDirEditor.exe
          copy README.md build_artifact\
          copy requirements.txt build_artifact\

      - name: Create artifact ZIP
        run: powershell Compress-Archive -Path build_artifact\* -DestinationPath EffDirEditor-Package-${{ github.run_number }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: EffDirEditor-Package-v${{ github.run_number }}
          path: EffDirEditor-Package-${{ github.run_number }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: EffDirEditor-Package-v${{ github.run_number }}
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Effect Dir Editor v${{ github.run_number }}
          body: |
            🚀 **New Release** of Effect Dir Editor v${{ github.run_number }}  
            - Automatic executable build  
            - Includes README and requirements.txt  
            - Bug fixes and improvements
          files: EffDirEditor-Package-${{ github.run_number }}.zip
