name: Build EffDirEditor EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name "EffDirEditor"

      - name: Read and bump version
        id: version
        run: |
          python - <<EOF
    import os, pathlib
    version_file = pathlib.Path("version.txt")
    version = version_file.read_text().strip()
    major, minor = map(int, version.split("."))
    new_version = f"{major}.{minor + 1}"
    version_file.write_text(new_version)
    with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
        fh.write(f"current={version}\n")
        fh.write(f"new={new_version}\n")
    EOF

      - name: Create zip package
        run: |
          mkdir dist_zip
          copy dist\EffDirEditor.exe dist_zip\
          copy README.md dist_zip\
          copy version.txt dist_zip\
          powershell Compress-Archive -Path dist_zip\* -DestinationPath EffDirEditor-Package-v${{ steps.version.outputs.current }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EffDirEditor-Package-v${{ steps.version.outputs.current }}
          path: EffDirEditor-Package-v${{ steps.version.outputs.current }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.current }}
          name: Effect Dir Editor v${{ steps.version.outputs.current }}
          body: |
            🚀 **Effect Dir Editor v${{ steps.version.outputs.current }}**
            - Automatic build from main branch
            - Includes latest features and fixes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
